// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for EstadoReporte.
const (
	Descartado EstadoReporte = "Descartado"
	Expirado   EstadoReporte = "Expirado"
	Pendiente  EstadoReporte = "Pendiente"
	Probable   EstadoReporte = "Probable"
	Resuelto   EstadoReporte = "Resuelto"
	Verificado EstadoReporte = "Verificado"
)

// Valid indicates whether the value is a known member of the EstadoReporte enum.
func (e EstadoReporte) Valid() bool {
	switch e {
	case Descartado:
		return true
	case Expirado:
		return true
	case Pendiente:
		return true
	case Probable:
		return true
	case Resuelto:
		return true
	case Verificado:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
	User        struct {
		CreatedAt time.Time           `json:"created_at"`
		Email     openapi_types.Email `json:"email"`
		Id        uuid.UUID           `json:"id"`
		RolId     int                 `json:"rol_id"`
		Username  string              `json:"username"`
	} `json:"user"`
}

// Comentario defines model for Comentario.
type Comentario struct {
	Comentario string    `json:"comentario"`
	CreatedAt  time.Time `json:"created_at"`
	Id         int       `json:"id"`
	ReporteId  uuid.UUID `json:"reporte_id"`
	UserId     uuid.UUID `json:"user_id"`
}

// CrearComentarioRequest defines model for CrearComentarioRequest.
type CrearComentarioRequest struct {
	Comentario string `json:"comentario"`
}

// CrearIncidenteRequest defines model for CrearIncidenteRequest.
type CrearIncidenteRequest struct {
	// Color Se usa el gris por defecto (#757575).
	//
	// Example: #EF6C33
	Color      *string  `json:"color,omitempty"`
	EstaActivo *bool    `json:"esta_activo,omitempty"`
	Nombre     string   `json:"nombre"`
	Radio      *float64 `json:"radio,omitempty"`

	// Tags Tags del catálogo del incidente. Los nombres no se pueden repetir (sin importar mayúsculas).
	Tags         *[]CrearTagRequest `json:"tags,omitempty"`
	TiempoLimite *int               `json:"tiempo_limite,omitempty"`
}

// CrearReporteRequest defines model for CrearReporteRequest.
type CrearReporteRequest struct {
	ImagePath   *string `json:"image_path,omitempty"`
	IncidenteId int     `json:"incidente_id"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
}

// CrearTagRequest Tag nuevo del catálogo. El incidente al que pertenece lo da el contexto (el incidente que se está creando), no el cliente.
type CrearTagRequest struct {
	Nombre string `json:"nombre"`
	Peso   *int   `json:"peso,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// EstadoReporte defines model for EstadoReporte.
type EstadoReporte string

// Foto defines model for Foto.
type Foto struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	ImagePath string    `json:"image_path"`
	UserId    uuid.UUID `json:"user_id"`
}

// Incidente defines model for Incidente.
type Incidente struct {
	// Color Example: #EF6C33
	Color        string        `json:"color"`
	EstaActivo   bool          `json:"esta_activo"`
	Id           int           `json:"id"`
	Nombre       string        `json:"nombre"`
	Radio        *float64      `json:"radio"`
	Tags         []TagCatalogo `json:"tags"`
	TiempoLimite *int          `json:"tiempo_limite"`
}

// Location defines model for Location.
type Location struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	UserId    uuid.UUID `json:"user_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// Reporte Detalle completo de un reporte.
type Reporte struct {
	Avistamientos int           `json:"avistamientos"`
	Comentarios   []Comentario  `json:"comentarios"`
	CreatedAt     time.Time     `json:"created_at"`
	EsHistorico   bool          `json:"es_historico"`
	EsOficial     bool          `json:"es_oficial"`
	EstadoActual  EstadoReporte `json:"estado_actual"`
	ExpiredAt     *time.Time    `json:"expired_at,omitempty"`
	Fotos         []Foto        `json:"fotos"`
	Id            uuid.UUID     `json:"id"`
	IncidenteId   int           `json:"incidente_id"`

	// Latitude Centroide de todas las locations (tabla puntos_origen).
	Latitude  float64    `json:"latitude"`
	Locations []Location `json:"locations"`

	// Longitude Centroide de todas las locations (tabla puntos_origen).
	Longitude float64   `json:"longitude"`
	Tags      []Tag     `json:"tags"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ReporteResumen Versión ligera de un reporte para pintar pines en el mapa.
type ReporteResumen struct {
	Avistamientos int           `json:"avistamientos"`
	EsOficial     bool          `json:"es_oficial"`
	EstadoActual  EstadoReporte `json:"estado_actual"`
	Id            uuid.UUID     `json:"id"`
	IncidenteId   int           `json:"incidente_id"`

	// Latitude Centroide del reporte (tabla puntos_origen).
	Latitude float64 `json:"latitude"`

	// Longitude Centroide del reporte (tabla puntos_origen).
	Longitude float64 `json:"longitude"`
}

// Tag defines model for Tag.
type Tag struct {
	// Count Cuántos usuarios han confirmado este tag en el reporte.
	Count  int    `json:"count"`
	Id     int    `json:"id"`
	Nombre string `json:"nombre"`
}

// TagCatalogo Tag del catálogo de un tipo de incidente (tabla tags), sin conteos por reporte.
type TagCatalogo struct {
	Id     int    `json:"id"`
	Nombre string `json:"nombre"`
	Peso   int    `json:"peso"`
}

// Usuario defines model for Usuario.
type Usuario struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        uuid.UUID           `json:"id"`
	RolId     int                 `json:"rol_id"`
	Username  string              `json:"username"`
}

// UsuarioMeResponse defines model for UsuarioMeResponse.
type UsuarioMeResponse struct {
	Email    openapi_types.Email `json:"email"`
	Id       uuid.UUID           `json:"id"`
	RolName  string              `json:"rol_name"`
	Username string              `json:"username"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListarReportesParams defines parameters for ListarReportes.
type ListarReportesParams struct {
	MinLat *float64 `form:"min_lat,omitempty" json:"min_lat,omitempty"`
	MaxLat *float64 `form:"max_lat,omitempty" json:"max_lat,omitempty"`
	MinLng *float64 `form:"min_lng,omitempty" json:"min_lng,omitempty"`
	MaxLng *float64 `form:"max_lng,omitempty" json:"max_lng,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CrearIncidenteJSONRequestBody defines body for CrearIncidente for application/json ContentType.
type CrearIncidenteJSONRequestBody = CrearIncidenteRequest

// CrearReporteJSONRequestBody defines body for CrearReporte for application/json ContentType.
type CrearReporteJSONRequestBody = CrearReporteRequest

// CrearComentarioJSONRequestBody defines body for CrearComentario for application/json ContentType.
type CrearComentarioJSONRequestBody = CrearComentarioRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /auth/login)
	Login(c *gin.Context)

	// (POST /auth/logout)
	Logout(c *gin.Context)

	// (GET /auth/me)
	Me(c *gin.Context)

	// (POST /auth/register)
	Register(c *gin.Context)

	// (POST /incidentes)
	CrearIncidente(c *gin.Context)

	// (GET /reportes)
	ListarReportes(c *gin.Context, params ListarReportesParams)

	// (POST /reportes)
	CrearReporte(c *gin.Context)

	// (GET /reportes/{reporteId})
	ObtenerReporte(c *gin.Context, reporteId uuid.UUID)

	// (PATCH /reportes/{reporteId}/avistamientos)
	AgregarAvistamiento(c *gin.Context, reporteId uuid.UUID)

	// (POST /reportes/{reporteId}/comentarios)
	CrearComentario(c *gin.Context, reporteId uuid.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// CrearIncidente operation middleware
func (siw *ServerInterfaceWrapper) CrearIncidente(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{"admin"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CrearIncidente(c)
}

// ListarReportes operation middleware
func (siw *ServerInterfaceWrapper) ListarReportes(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarReportesParams

	// ------------- Optional query parameter "min_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lat", c.Request.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter min_lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "max_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lat", c.Request.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter max_lat: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "min_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lng", c.Request.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter min_lng: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "max_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lng", c.Request.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter max_lng: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListarReportes(c, params)
}

// CrearReporte operation middleware
func (siw *ServerInterfaceWrapper) CrearReporte(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CrearReporte(c)
}

// ObtenerReporte operation middleware
func (siw *ServerInterfaceWrapper) ObtenerReporte(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "reporteId" -------------
	var reporteId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reporteId", c.Param("reporteId"), &reporteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter reporteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ObtenerReporte(c, reporteId)
}

// AgregarAvistamiento operation middleware
func (siw *ServerInterfaceWrapper) AgregarAvistamiento(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "reporteId" -------------
	var reporteId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reporteId", c.Param("reporteId"), &reporteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter reporteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AgregarAvistamiento(c, reporteId)
}

// CrearComentario operation middleware
func (siw *ServerInterfaceWrapper) CrearComentario(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "reporteId" -------------
	var reporteId uuid.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reporteId", c.Param("reporteId"), &reporteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter reporteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CrearComentario(c, reporteId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/incidentes", wrapper.CrearIncidente)
	router.GET(options.BaseURL+"/reportes", wrapper.ListarReportes)
	router.POST(options.BaseURL+"/reportes", wrapper.CrearReporte)
	router.GET(options.BaseURL+"/reportes/:reporteId", wrapper.ObtenerReporte)
	router.PATCH(options.BaseURL+"/reportes/:reporteId/avistamientos", wrapper.AgregarAvistamiento)
	router.POST(options.BaseURL+"/reportes/:reporteId/comentarios", wrapper.CrearComentario)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type MeRequestObject struct {
}

type MeResponseObject interface {
	VisitMeResponse(w http.ResponseWriter) error
}

type Me200JSONResponse UsuarioMeResponse

func (response Me200JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Me401JSONResponse ErrorResponse

func (response Me401JSONResponse) VisitMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ErrorResponse

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CrearIncidenteRequestObject struct {
	Body *CrearIncidenteJSONRequestBody
}

type CrearIncidenteResponseObject interface {
	VisitCrearIncidenteResponse(w http.ResponseWriter) error
}

type CrearIncidente201JSONResponse Incidente

func (response CrearIncidente201JSONResponse) VisitCrearIncidenteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CrearIncidente400JSONResponse ErrorResponse

func (response CrearIncidente400JSONResponse) VisitCrearIncidenteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CrearIncidente401JSONResponse ErrorResponse

func (response CrearIncidente401JSONResponse) VisitCrearIncidenteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CrearIncidente403JSONResponse ErrorResponse

func (response CrearIncidente403JSONResponse) VisitCrearIncidenteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CrearIncidente409JSONResponse ErrorResponse

func (response CrearIncidente409JSONResponse) VisitCrearIncidenteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReportesRequestObject struct {
	Params ListarReportesParams
}

type ListarReportesResponseObject interface {
	VisitListarReportesResponse(w http.ResponseWriter) error
}

type ListarReportes200JSONResponse []ReporteResumen

func (response ListarReportes200JSONResponse) VisitListarReportesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReportes400JSONResponse ErrorResponse

func (response ListarReportes400JSONResponse) VisitListarReportesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReportes401JSONResponse ErrorResponse

func (response ListarReportes401JSONResponse) VisitListarReportesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReporteRequestObject struct {
	Body *CrearReporteJSONRequestBody
}

type CrearReporteResponseObject interface {
	VisitCrearReporteResponse(w http.ResponseWriter) error
}

type CrearReporte201JSONResponse Reporte

func (response CrearReporte201JSONResponse) VisitCrearReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReporte400JSONResponse ErrorResponse

func (response CrearReporte400JSONResponse) VisitCrearReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReporte401JSONResponse ErrorResponse

func (response CrearReporte401JSONResponse) VisitCrearReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReporteRequestObject struct {
	ReporteId uuid.UUID `json:"reporteId"`
}

type ObtenerReporteResponseObject interface {
	VisitObtenerReporteResponse(w http.ResponseWriter) error
}

type ObtenerReporte200JSONResponse Reporte

func (response ObtenerReporte200JSONResponse) VisitObtenerReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReporte401JSONResponse ErrorResponse

func (response ObtenerReporte401JSONResponse) VisitObtenerReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReporte404JSONResponse ErrorResponse

func (response ObtenerReporte404JSONResponse) VisitObtenerReporteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AgregarAvistamientoRequestObject struct {
	ReporteId uuid.UUID `json:"reporteId"`
}

type AgregarAvistamientoResponseObject interface {
	VisitAgregarAvistamientoResponse(w http.ResponseWriter) error
}

type AgregarAvistamiento200JSONResponse Reporte

func (response AgregarAvistamiento200JSONResponse) VisitAgregarAvistamientoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AgregarAvistamiento400JSONResponse ErrorResponse

func (response AgregarAvistamiento400JSONResponse) VisitAgregarAvistamientoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AgregarAvistamiento401JSONResponse ErrorResponse

func (response AgregarAvistamiento401JSONResponse) VisitAgregarAvistamientoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AgregarAvistamiento404JSONResponse ErrorResponse

func (response AgregarAvistamiento404JSONResponse) VisitAgregarAvistamientoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CrearComentarioRequestObject struct {
	ReporteId uuid.UUID `json:"reporteId"`
	Body      *CrearComentarioJSONRequestBody
}

type CrearComentarioResponseObject interface {
	VisitCrearComentarioResponse(w http.ResponseWriter) error
}

type CrearComentario201JSONResponse Comentario

func (response CrearComentario201JSONResponse) VisitCrearComentarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CrearComentario400JSONResponse ErrorResponse

func (response CrearComentario400JSONResponse) VisitCrearComentarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CrearComentario401JSONResponse ErrorResponse

func (response CrearComentario401JSONResponse) VisitCrearComentarioResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)

	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (GET /auth/me)
	Me(ctx context.Context, request MeRequestObject) (MeResponseObject, error)

	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)

	// (POST /incidentes)
	CrearIncidente(ctx context.Context, request CrearIncidenteRequestObject) (CrearIncidenteResponseObject, error)

	// (GET /reportes)
	ListarReportes(ctx context.Context, request ListarReportesRequestObject) (ListarReportesResponseObject, error)

	// (POST /reportes)
	CrearReporte(ctx context.Context, request CrearReporteRequestObject) (CrearReporteResponseObject, error)

	// (GET /reportes/{reporteId})
	ObtenerReporte(ctx context.Context, request ObtenerReporteRequestObject) (ObtenerReporteResponseObject, error)

	// (PATCH /reportes/{reporteId}/avistamientos)
	AgregarAvistamiento(ctx context.Context, request AgregarAvistamientoRequestObject) (AgregarAvistamientoResponseObject, error)

	// (POST /reportes/{reporteId}/comentarios)
	CrearComentario(ctx context.Context, request CrearComentarioRequestObject) (CrearComentarioResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Me operation middleware
func (sh *strictHandler) Me(ctx *gin.Context) {
	var request MeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Me(ctx, request.(MeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Me")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(MeResponseObject); ok {
		if err := validResponse.VisitMeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(ctx *gin.Context) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CrearIncidente operation middleware
func (sh *strictHandler) CrearIncidente(ctx *gin.Context) {
	var request CrearIncidenteRequestObject

	var body CrearIncidenteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CrearIncidente(ctx, request.(CrearIncidenteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CrearIncidente")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CrearIncidenteResponseObject); ok {
		if err := validResponse.VisitCrearIncidenteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListarReportes operation middleware
func (sh *strictHandler) ListarReportes(ctx *gin.Context, params ListarReportesParams) {
	var request ListarReportesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListarReportes(ctx, request.(ListarReportesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListarReportes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListarReportesResponseObject); ok {
		if err := validResponse.VisitListarReportesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CrearReporte operation middleware
func (sh *strictHandler) CrearReporte(ctx *gin.Context) {
	var request CrearReporteRequestObject

	var body CrearReporteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CrearReporte(ctx, request.(CrearReporteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CrearReporte")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CrearReporteResponseObject); ok {
		if err := validResponse.VisitCrearReporteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ObtenerReporte operation middleware
func (sh *strictHandler) ObtenerReporte(ctx *gin.Context, reporteId uuid.UUID) {
	var request ObtenerReporteRequestObject

	request.ReporteId = reporteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ObtenerReporte(ctx, request.(ObtenerReporteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ObtenerReporte")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ObtenerReporteResponseObject); ok {
		if err := validResponse.VisitObtenerReporteResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AgregarAvistamiento operation middleware
func (sh *strictHandler) AgregarAvistamiento(ctx *gin.Context, reporteId uuid.UUID) {
	var request AgregarAvistamientoRequestObject

	request.ReporteId = reporteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AgregarAvistamiento(ctx, request.(AgregarAvistamientoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AgregarAvistamiento")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(AgregarAvistamientoResponseObject); ok {
		if err := validResponse.VisitAgregarAvistamientoResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CrearComentario operation middleware
func (sh *strictHandler) CrearComentario(ctx *gin.Context, reporteId uuid.UUID) {
	var request CrearComentarioRequestObject

	request.ReporteId = reporteId

	var body CrearComentarioJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CrearComentario(ctx, request.(CrearComentarioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CrearComentario")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CrearComentarioResponseObject); ok {
		if err := validResponse.VisitCrearComentarioResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvbjtu4GX4VgtmLBHA8ns3Zd+kkAVJk2yBJtyiCqfFb+q1hSpEKSU0zCPww8wy96+28WEFSkkWb8iHj",
	"sd2NsdiMZEnkf/j+s/SdJjIvpEBhNB1+pzq5wBzc4cvSXHxAXUih0Z4XShaoDEN3FZIEtR4Z+S8U9txc",
	"FUiHVBvFREanPYrfCqZQj1j7MhMGM1T2unty5H+PPF5qVPbCLwondEjvnczoPKmIPPmbLkExSafTHlX4",
	"tWQKUzr8HNIW7BSQVW1y3qt3l+MvmBi7+5nMURi3+ALnSXBtgfBEIRhMR2Ds5YlUuT2iKRh8aFhuaVh4",
	"hqVxGSkspDI4YmmwVlmyNLaMZWe9e+cE5m5pbTZbqtdmN2AuKjaFoGay+4BfS9RmlQhz+PYORWYu6PDJ",
	"YNCjORP1+ekqylsrdRL0ViQsRWFwCT1cOrSlqBPFCsOkoEP6EUmpgSAnmWKaFFKRFCeYGEnu33v2xP73",
	"oO8wBXnB7c73Xr95evboEe3RAoxBZVf5573Pg4cvXj58Aw8n59+fTn+JqQ61gREkhl1KT8cESm7o0KgS",
	"m9vHUnIEYe8XMh8rnJPe6Urp9aiClMkAIaksxxype5LlZU6Hg+Y5Uebjylwh04sS+gSZJilykoC5ueYy",
	"k+6M1RLvk3dSE0+s/Us0kqLEFAVRWKBhitzXTBCWW+yBIjlc3fxXJyUH7UTLDOZ6lR9wWv4EWa3fac9K",
	"5a1/9MmMG1AKrhwzDPNCjjjLmamF6Fl/9Ouzp8+iomjMcg6BlSY60ffBm1Un9lgOGY4KsAr7vkp7jWBH",
	"XS6Dg2GmTLFDxTWfLwYtJh++iGmcS5Gts9Tp82Ct0+eLi827mzYXLZLbe3bKs6XnGByJKPFShpjsk9ct",
	"TBLg5GuJxOoABSZIuCSpM/NECoPfrHm3Qezu1khQm5trYl2gSOWDnoWzfYYzh3Tam1Ns1ESfrLbQAnXo",
	"A05b4j29DR5fKyVVd0jPUWvIYuF4bov6xuge2kAqK9DbpVBYuj/T9yhSJynao++VHIOH0e+o2IQlkEra",
	"ox9Ql8iNPXyFOgFl/O+vbdC2h+cReb2RJhaltxiGQxPdcthtLR6E3eWRtolpS4LZ9sPSYhzqEll3fNok",
	"IomSc4eTMA4uRqW1wsQnyM7AgPUIdNos1h0UOnbvMjyntorv+dVqLnuVdirKQwHH9PxOJuCd210CfHnQ",
	"2DQyLNx/OwOJhocNTOWdzJjoDL+YA+MBZf6XmGMGrf8tVbraQdZLNE/E6PqAGdMG1bZJa4WX5x1FgoB8",
	"89yxg8dmvZXsNiEhDNqv0ADnSKzFcjQ2dpPS5YdSxeIqXDJtILexROo4nmdVwfreofo7aj3bOo45jB+x",
	"QNSjC6aNVCzp8KioR3LCEga867oNitZnlMDXZaoSph5VT1fnszp9My4m0vyAZN1T7t+YNNescTfLgEOk",
	"naEwSrIULcSMTEETbv+vfKwm9w2MOZCitNAaScUyFK4MWcspVqtsLJfmyeYoJp/A6e6Qr01DbIz2skg3",
	"tJRophSWDaEfmDOtwI7mjaYzprQsOiA69Cg1/psgPlP9Esdnc9scxaL2fkel2c1/BOEsQwWh+yMFKCAF",
	"s3vbP6gJClt25FDAD/nGXfuXHds1byR3O2MW2Y42WwPp8+iNIH8G9bWraWurkeKhFJHC+qy8ubabkdK3",
	"XDW5AGHL5QlTOaTS1sZIDGQVOlvBO1JObVIzPNkwLQmzcM9OB/dNMRDtI8x3taxRGla4w1lroNK7dQQP",
	"esS2slwPQfpuYWcOs10RzHoGG/QJQkG5BWJyqnvsW6k/Nsho13QbSvJOh9HOdNcATSShrVZfWWJUQvoN",
	"u5srd8N6B3vb4t0dxhiu/T6U5sL/ow56UhTQW97Z2CjYhtu6c6QOr/AMqFRVFbp1Qg+0DI0i4ejclji3",
	"mMRGOS6x+D+mr+toDBznw+vPh6OiVAiq9Uu3I9rZ1LgmE5WSagnOtzIwiXRHfrZhRi2CJq2uUdH8sAwU",
	"x9H9cXS/9dF9BJLsOHL7KUZuS9qyxyHcjw7hFhqF3sFXp93u/fh2zNr9vFW92F28i7FAgzpO/Y5Tv+PU",
	"7zj1+9mmfl2ecKSOc8DjHPBw5oAWqpiUipmrj1aJHj9jBIXKfgEyO3tTc/Dnv3+iFcAdZtzVGUMXxhR0",
	"OnW6nPhwx4yriT6xLyUIIH4iDuTl+7e0Ry8t7p1IT/uD/sCKXRYooGB0SB/1B/2qiLpwlJ3YNuSJ663b",
	"00L6rNGC31nj25QO/Stf1AsUtfmTTK98mSYM+vEmFAVn3n5Pvmif2nsQbzRKCHv801CJRpXofvD9I0f+",
	"r4PB3VASDmEcJSFenUwIfmNGaheKH98BKXMdswgZr8COkZm4vLnmLJXaU3K6B0rOFKYorLXgjCDQgUnQ",
	"4edze96gTpZmKezs9QWVP471p7yvT1ApSGHJpr6vnWFkv9+Q7gpesb5/RKbVIJRAaff3pcTeFPyXOTqm",
	"M6HWU69uXdZvZ+7CiyzM4NZyJKd7ciS1jhOFjXoPx5O82AMlrzlxQyVyBdVHIl6jysMuYtmztmIbgQv+",
	"CWwG6D9oWXj1pE8+Si59Xgip7TD4DRVqm2+EaA6/g7tjTK/Rxt8TwKPd3IhCG0kdHMjJ/aJP8EufuKYm",
	"yYETl1mmkkj3FlLVnE+lfnA4ntfS8Wg/hlkFLjvAMAwFEiW5taPAZPbnOv4BNiXTxtV6s9fKEikIaqzG",
	"L/M+JMzPP1PHCz2fet9S12CttCHcs3ohVRPfBNfeh9S1JPnI7KgnB+G/ibu5tn7okmk25tgjE8aNrUSl",
	"Isg5LLqad7Ymqb961C51V5CjQaUd6cyS8LVEdUV71I/tac7EiLuKeybf27Rnp72OfeDbbvax/Ihs3X3W",
	"6hEv4Wi7O53fMqfcqAvW2R5Z6CdFKhqLNGvL9SLHqiaW9PY6Mtz218l3nBGsmPrsKRuYx15MnJV8DjTZ",
	"PZyqqpblyffq6G067axb/zo2KLCFvViIqF4iqfxcsyqdR0rU83UMNs93UC5vgioUdmt1UFWypePxHuio",
	"ZSJkIJZueJ0sNLkLMMnFItxeZgozUC9bt/+EmGuzT8CJ5OjQ/r8NYG7gvSTMn7Vf0twp8u8uqVjrJdI9",
	"pRZdrxNEutDN1WOOsSzHWFoB29L3fwMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
