// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comentario.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const createComentario = `-- name: CreateComentario :one
INSERT INTO comentarios (reporte_id, user_id, comentario)
VALUES ($1, $2, $3)
RETURNING id, reporte_id, user_id, comentario, created_at
`

type CreateComentarioParams struct {
	ReporteID  uuid.UUID `json:"reporte_id"`
	UserID     uuid.UUID `json:"user_id"`
	Comentario string    `json:"comentario"`
}

func (q *Queries) CreateComentario(ctx context.Context, arg CreateComentarioParams) (Comentario, error) {
	row := q.db.QueryRow(ctx, createComentario, arg.ReporteID, arg.UserID, arg.Comentario)
	var i Comentario
	err := row.Scan(
		&i.ID,
		&i.ReporteID,
		&i.UserID,
		&i.Comentario,
		&i.CreatedAt,
	)
	return i, err
}

const listComentariosByReporteId = `-- name: ListComentariosByReporteId :many
SELECT id, reporte_id, user_id, comentario, created_at FROM comentarios WHERE reporte_id = $1 ORDER BY created_at
`

func (q *Queries) ListComentariosByReporteId(ctx context.Context, reporteID uuid.UUID) ([]Comentario, error) {
	rows, err := q.db.Query(ctx, listComentariosByReporteId, reporteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comentario
	for rows.Next() {
		var i Comentario
		if err := rows.Scan(
			&i.ID,
			&i.ReporteID,
			&i.UserID,
			&i.Comentario,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
