// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidente.sql

package domain

import (
	"context"
)

const createIncidente = `-- name: CreateIncidente :one
INSERT INTO incidentes (nombre, tiempo_limite, radio, esta_activo, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nombre, tiempo_limite, radio, esta_activo, color
`

type CreateIncidenteParams struct {
	Nombre       string   `json:"nombre"`
	TiempoLimite *int     `json:"tiempo_limite"`
	Radio        *float64 `json:"radio"`
	EstaActivo   bool     `json:"esta_activo"`
	Color        string   `json:"color"`
}

func (q *Queries) CreateIncidente(ctx context.Context, arg CreateIncidenteParams) (Incidente, error) {
	row := q.db.QueryRow(ctx, createIncidente,
		arg.Nombre,
		arg.TiempoLimite,
		arg.Radio,
		arg.EstaActivo,
		arg.Color,
	)
	var i Incidente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.TiempoLimite,
		&i.Radio,
		&i.EstaActivo,
		&i.Color,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (incidente_id, nombre, peso)
VALUES ($1, $2, $3)
RETURNING id, incidente_id, nombre, peso
`

type CreateTagParams struct {
	IncidenteID int    `json:"incidente_id"`
	Nombre      string `json:"nombre"`
	Peso        int    `json:"peso"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.IncidenteID, arg.Nombre, arg.Peso)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.IncidenteID,
		&i.Nombre,
		&i.Peso,
	)
	return i, err
}

const getIncidenteById = `-- name: GetIncidenteById :one
SELECT id, nombre, tiempo_limite, radio, esta_activo, color FROM incidentes WHERE id = $1
`

func (q *Queries) GetIncidenteById(ctx context.Context, id int) (Incidente, error) {
	row := q.db.QueryRow(ctx, getIncidenteById, id)
	var i Incidente
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.TiempoLimite,
		&i.Radio,
		&i.EstaActivo,
		&i.Color,
	)
	return i, err
}
