// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package domain

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Estado string

const (
	EstadoSinrevisar Estado = "Sin revisar"
	EstadoEnrevision Estado = "En revision"
	EstadoArreglado  Estado = "Arreglado"
	EstadoExpirado   Estado = "Expirado"
	EstadoOficial    Estado = "Oficial"
)

func (e *Estado) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Estado(s)
	case string:
		*e = Estado(s)
	default:
		return fmt.Errorf("unsupported scan type for Estado: %T", src)
	}
	return nil
}

type NullEstado struct {
	Estado Estado `json:"estado"`
	Valid  bool   `json:"valid"` // Valid is true if Estado is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstado) Scan(value interface{}) error {
	if value == nil {
		ns.Estado, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Estado.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstado) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Estado), nil
}

type UserState string

const (
	UserStatePendiente  UserState = "Pendiente"
	UserStateEnrevisin  UserState = "En revisión"
	UserStateVerificado UserState = "Verificado"
	UserStateSuspendido UserState = "Suspendido"
)

func (e *UserState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserState(s)
	case string:
		*e = UserState(s)
	default:
		return fmt.Errorf("unsupported scan type for UserState: %T", src)
	}
	return nil
}

type NullUserState struct {
	UserState UserState `json:"user_state"`
	Valid     bool      `json:"valid"` // Valid is true if UserState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserState) Scan(value interface{}) error {
	if value == nil {
		ns.UserState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserState), nil
}

type AuthProvider struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID *string   `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Comentario struct {
	ID         int       `json:"id"`
	ReporteID  uuid.UUID `json:"reporte_id"`
	UserID     uuid.UUID `json:"user_id"`
	Comentario string    `json:"comentario"`
	CreatedAt  time.Time `json:"created_at"`
}

type FotosReporte struct {
	ID        int       `json:"id"`
	ReporteID uuid.UUID `json:"reporte_id"`
	ImagePath string    `json:"image_path"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Incidente struct {
	ID           int            `json:"id"`
	Nombre       string         `json:"nombre"`
	TiempoLimite pgtype.Int2    `json:"tiempo_limite"`
	Radio        pgtype.Numeric `json:"radio"`
}

type IncidenteTag struct {
	ID        int       `json:"id"`
	ReporteID uuid.UUID `json:"reporte_id"`
	TagID     int       `json:"tag_id"`
	AddedBy   uuid.UUID `json:"added_by"`
	CreatedAt time.Time `json:"created_at"`
}

type Location struct {
	ID        int            `json:"id"`
	ReporteID uuid.UUID      `json:"reporte_id"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
	UserID    uuid.UUID      `json:"user_id"`
	CreatedAt time.Time      `json:"created_at"`
}

type Log struct {
	ID          uuid.UUID      `json:"id"`
	IncidenteID int            `json:"incidente_id"`
	Longitude   pgtype.Numeric `json:"longitude"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Peso        int            `json:"peso"`
	StartedAt   time.Time      `json:"started_at"`
	FinishedAt  time.Time      `json:"finished_at"`
}

type PuntosOrigen struct {
	ReporteID   uuid.UUID      `json:"reporte_id"`
	Latitude    pgtype.Numeric `json:"latitude"`
	Longitude   pgtype.Numeric `json:"longitude"`
	SampleCount int            `json:"sample_count"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Reporte struct {
	ID            uuid.UUID  `json:"id"`
	IncidenteID   int        `json:"incidente_id"`
	Avistamientos int        `json:"avistamientos"`
	EsHistorico   bool       `json:"es_historico"`
	EstadoActual  Estado     `json:"estado_actual"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	ExpiredAt     *time.Time `json:"expired_at"`
}

type ReporteTagCount struct {
	ReporteID uuid.UUID `json:"reporte_id"`
	TagID     int       `json:"tag_id"`
	Count     int       `json:"count"`
}

type ReportesScore struct {
	ReporteID  uuid.UUID `json:"reporte_id"`
	TotalScore int       `json:"total_score"`
}

type Role struct {
	ID     int    `json:"id"`
	Nombre string `json:"nombre"`
}

type Tag struct {
	ID          int    `json:"id"`
	IncidenteID int    `json:"incidente_id"`
	Nombre      string `json:"nombre"`
	Peso        int    `json:"peso"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	Email        *string       `json:"email"`
	Phone        *string       `json:"phone"`
	Username     string        `json:"username"`
	RolID        int           `json:"rol_id"`
	PasswordHash *string       `json:"password_hash"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	State        NullUserState `json:"state"`
}

type UsersReport struct {
	ID        int       `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ReporteID uuid.UUID `json:"reporte_id"`
}
