// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporte.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const createFotoReporte = `-- name: CreateFotoReporte :one
INSERT INTO fotos_reportes (reporte_id, image_path, user_id)
VALUES ($1, $2, $3)
RETURNING id, reporte_id, image_path, user_id, created_at
`

type CreateFotoReporteParams struct {
	ReporteID uuid.UUID `json:"reporte_id"`
	ImagePath string    `json:"image_path"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateFotoReporte(ctx context.Context, arg CreateFotoReporteParams) (FotosReporte, error) {
	row := q.db.QueryRow(ctx, createFotoReporte, arg.ReporteID, arg.ImagePath, arg.UserID)
	var i FotosReporte
	err := row.Scan(
		&i.ID,
		&i.ReporteID,
		&i.ImagePath,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO location (reporte_id, latitude, longitude, user_id)
VALUES ($1, $3::float8, $4::float8, $2)
RETURNING id, reporte_id, latitude, longitude, user_id, created_at
`

type CreateLocationParams struct {
	ReporteID uuid.UUID `json:"reporte_id"`
	UserID    uuid.UUID `json:"user_id"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.ReporteID,
		arg.UserID,
		arg.Latitude,
		arg.Longitude,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ReporteID,
		&i.Latitude,
		&i.Longitude,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const createReporte = `-- name: CreateReporte :one
INSERT INTO reporte (incidente_id, es_oficial)
VALUES ($1, $2)
RETURNING id, incidente_id, avistamientos, es_historico, es_oficial, estado_actual, created_at, updated_at, expired_at
`

type CreateReporteParams struct {
	IncidenteID int  `json:"incidente_id"`
	EsOficial   bool `json:"es_oficial"`
}

func (q *Queries) CreateReporte(ctx context.Context, arg CreateReporteParams) (Reporte, error) {
	row := q.db.QueryRow(ctx, createReporte, arg.IncidenteID, arg.EsOficial)
	var i Reporte
	err := row.Scan(
		&i.ID,
		&i.IncidenteID,
		&i.Avistamientos,
		&i.EsHistorico,
		&i.EsOficial,
		&i.EstadoActual,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const listLocationsByReporteId = `-- name: ListLocationsByReporteId :many
SELECT id, reporte_id, latitude, longitude, user_id, created_at FROM location WHERE reporte_id = $1
`

func (q *Queries) ListLocationsByReporteId(ctx context.Context, reporteID uuid.UUID) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocationsByReporteId, reporteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ReporteID,
			&i.Latitude,
			&i.Longitude,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
