// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package domain

import (
	"context"
)

const getDefaultRole = `-- name: GetDefaultRole :one
SELECT id, nombre FROM roles
WHERE nombre = 'ciudadano'
`

func (q *Queries) GetDefaultRole(ctx context.Context) (Role, error) {
	row := q.db.QueryRow(ctx, getDefaultRole)
	var i Role
	err := row.Scan(&i.ID, &i.Nombre)
	return i, err
}
