// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package domain

import (
	"context"

	"github.com/google/uuid"
)

const createLocalAuthProvider = `-- name: CreateLocalAuthProvider :exec
INSERT INTO auth_providers (user_id, provider)
VALUES ($1, 'local')
`

// Se inserta junto con el usuario dentro de la misma transacción (ver
// database.Store.CreateUserWithLocalProvider), para que nunca quede un
// usuario sin forma de autenticarse ni un auth_provider huérfano.
func (q *Queries) CreateLocalAuthProvider(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createLocalAuthProvider, userID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, rol_id, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, phone, username, rol_id, password_hash, created_at, updated_at, state
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	Username     string  `json:"username"`
	RolID        int     `json:"rol_id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.RolID,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.RolID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, username, rol_id, password_hash, created_at, updated_at, state FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.RolID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, username, rol_id, password_hash, created_at, updated_at, state FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Username,
		&i.RolID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.State,
	)
	return i, err
}
