openapi: 3.0.3
info:
  title: Tijuana Reporta API
  version: 1.0.0

paths:
  /reportes/{reporteId}/comentarios:
    $ref: './paths/comentarios.yaml#/crearComentario'

components:
  schemas:
    Comentario:
      $ref: './schemas/comentarios/comentario.yaml'
    CrearComentarioRequest:
      $ref: './schemas/comentarios/crear_comentario_request.yaml'
    ErrorResponse:
      $ref: './schemas/error_response.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT